apiVersion: v1
kind: ConfigMap
metadata:
  name: tomlord-io-config
  namespace: tomlord-io
data:
  PORT: "8080"
  APP_ENV: "production"
  BLUEPRINT_DB_PORT: "5432"
  BLUEPRINT_DB_SCHEMA: "public"
  # TODO:[PRODUCTION] Update these with your actual production domains
  ALLOWED_ORIGINS: "https://tomlord.fyi"
  FRONTEND_URL: "https://tomlord.fyi"
  # TODO:[PRODUCTION] Add any additional production-specific configurations
  # Non-sensitive configurations only
  # Sensitive data should go in secrets 