// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkVisitorHash = `-- name: CheckVisitorHash :one
SELECT EXISTS(SELECT 1 FROM visitor_hashes WHERE date = $1 AND hash = $2) AS exists
`

type CheckVisitorHashParams struct {
	Date pgtype.Date `json:"date"`
	Hash string      `json:"hash"`
}

func (q *Queries) CheckVisitorHash(ctx context.Context, arg CheckVisitorHashParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkVisitorHash, arg.Date, arg.Hash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getRecentVisitCounts = `-- name: GetRecentVisitCounts :many
SELECT date, visit_count FROM daily_visits
WHERE date >= $1
ORDER BY date DESC
`

func (q *Queries) GetRecentVisitCounts(ctx context.Context, date pgtype.Date) ([]DailyVisit, error) {
	rows, err := q.db.Query(ctx, getRecentVisitCounts, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyVisit{}
	for rows.Next() {
		var i DailyVisit
		if err := rows.Scan(&i.Date, &i.VisitCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodayVisitCount = `-- name: GetTodayVisitCount :one
SELECT visit_count FROM daily_visits WHERE date = $1
`

func (q *Queries) GetTodayVisitCount(ctx context.Context, date pgtype.Date) (int32, error) {
	row := q.db.QueryRow(ctx, getTodayVisitCount, date)
	var visit_count int32
	err := row.Scan(&visit_count)
	return visit_count, err
}

const getTotalVisitCount = `-- name: GetTotalVisitCount :one
SELECT COALESCE(SUM(visit_count), 0)::bigint AS total FROM daily_visits
`

func (q *Queries) GetTotalVisitCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalVisitCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const insertVisitorHash = `-- name: InsertVisitorHash :exec
INSERT INTO visitor_hashes (date, hash) VALUES ($1, $2)
`

type InsertVisitorHashParams struct {
	Date pgtype.Date `json:"date"`
	Hash string      `json:"hash"`
}

func (q *Queries) InsertVisitorHash(ctx context.Context, arg InsertVisitorHashParams) error {
	_, err := q.db.Exec(ctx, insertVisitorHash, arg.Date, arg.Hash)
	return err
}

const upsertDailyVisit = `-- name: UpsertDailyVisit :one
INSERT INTO daily_visits (date, visit_count) VALUES ($1, 1)
ON CONFLICT (date) DO UPDATE SET visit_count = daily_visits.visit_count + 1
RETURNING visit_count
`

func (q *Queries) UpsertDailyVisit(ctx context.Context, date pgtype.Date) (int32, error) {
	row := q.db.QueryRow(ctx, upsertDailyVisit, date)
	var visit_count int32
	err := row.Scan(&visit_count)
	return visit_count, err
}
