// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: blogs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBlogs = `-- name: CountBlogs :one
SELECT COUNT(*) FROM blogs
WHERE is_published = true
`

func (q *Queries) CountBlogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBlogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBlogsByTag = `-- name: CountBlogsByTag :one
SELECT COUNT(*) FROM blogs
WHERE is_published = true AND $1 = ANY(tags)
`

func (q *Queries) CountBlogsByTag(ctx context.Context, tags []string) (int64, error) {
	row := q.db.QueryRow(ctx, countBlogsByTag, tags)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBlog = `-- name: CreateBlog :one
INSERT INTO blogs (title, slug, date, lang, duration, tags, description, is_published, content)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, slug, date, lang, duration, tags, description, is_published, created_at, updated_at, content
`

type CreateBlogParams struct {
	Title       string      `json:"title"`
	Slug        string      `json:"slug"`
	Date        pgtype.Date `json:"date"`
	Lang        string      `json:"lang"`
	Duration    string      `json:"duration"`
	Tags        []string    `json:"tags"`
	Description pgtype.Text `json:"description"`
	IsPublished pgtype.Bool `json:"is_published"`
	Content     pgtype.Text `json:"content"`
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error) {
	row := q.db.QueryRow(ctx, createBlog,
		arg.Title,
		arg.Slug,
		arg.Date,
		arg.Lang,
		arg.Duration,
		arg.Tags,
		arg.Description,
		arg.IsPublished,
		arg.Content,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Date,
		&i.Lang,
		&i.Duration,
		&i.Tags,
		&i.Description,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Content,
	)
	return i, err
}

const deleteBlogBySlug = `-- name: DeleteBlogBySlug :exec
DELETE FROM blogs
WHERE slug = $1
`

func (q *Queries) DeleteBlogBySlug(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteBlogBySlug, slug)
	return err
}

const getAllBlogs = `-- name: GetAllBlogs :many
SELECT id, title, slug, date, lang, duration, tags, description, is_published, created_at, updated_at, content FROM blogs
ORDER BY date DESC
LIMIT $1 OFFSET $2
`

type GetAllBlogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllBlogs(ctx context.Context, arg GetAllBlogsParams) ([]Blog, error) {
	rows, err := q.db.Query(ctx, getAllBlogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Blog{}
	for rows.Next() {
		var i Blog
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Date,
			&i.Lang,
			&i.Duration,
			&i.Tags,
			&i.Description,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlogByID = `-- name: GetBlogByID :one
SELECT id, title, slug, date, lang, duration, tags, description, is_published, created_at, updated_at, content FROM blogs
WHERE id = $1
`

func (q *Queries) GetBlogByID(ctx context.Context, id pgtype.UUID) (Blog, error) {
	row := q.db.QueryRow(ctx, getBlogByID, id)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Date,
		&i.Lang,
		&i.Duration,
		&i.Tags,
		&i.Description,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Content,
	)
	return i, err
}

const getBlogBySlug = `-- name: GetBlogBySlug :one
SELECT id, title, slug, date, lang, duration, tags, description, is_published, created_at, updated_at, content FROM blogs
WHERE slug = $1
`

func (q *Queries) GetBlogBySlug(ctx context.Context, slug string) (Blog, error) {
	row := q.db.QueryRow(ctx, getBlogBySlug, slug)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Date,
		&i.Lang,
		&i.Duration,
		&i.Tags,
		&i.Description,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Content,
	)
	return i, err
}

const getBlogWithMessageCountBySlug = `-- name: GetBlogWithMessageCountBySlug :one
SELECT
    b.id, b.title, b.slug, b.date, b.lang, b.duration, b.tags, b.description, b.is_published, b.created_at, b.updated_at, b.content,
    COALESCE(msg_count.count, 0) as message_count
FROM blogs b
LEFT JOIN (
    SELECT post_slug, COUNT(*) as count
    FROM messages
    GROUP BY post_slug
) msg_count ON b.slug = msg_count.post_slug
WHERE b.slug = $1
`

type GetBlogWithMessageCountBySlugRow struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	Date         pgtype.Date        `json:"date"`
	Lang         string             `json:"lang"`
	Duration     string             `json:"duration"`
	Tags         []string           `json:"tags"`
	Description  pgtype.Text        `json:"description"`
	IsPublished  pgtype.Bool        `json:"is_published"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Content      pgtype.Text        `json:"content"`
	MessageCount int64              `json:"message_count"`
}

func (q *Queries) GetBlogWithMessageCountBySlug(ctx context.Context, slug string) (GetBlogWithMessageCountBySlugRow, error) {
	row := q.db.QueryRow(ctx, getBlogWithMessageCountBySlug, slug)
	var i GetBlogWithMessageCountBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Date,
		&i.Lang,
		&i.Duration,
		&i.Tags,
		&i.Description,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Content,
		&i.MessageCount,
	)
	return i, err
}

const getBlogs = `-- name: GetBlogs :many
SELECT id, title, slug, date, lang, duration, tags, description, is_published, created_at, updated_at, content FROM blogs
WHERE is_published = true
ORDER BY date DESC
LIMIT $1 OFFSET $2
`

type GetBlogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetBlogs(ctx context.Context, arg GetBlogsParams) ([]Blog, error) {
	rows, err := q.db.Query(ctx, getBlogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Blog{}
	for rows.Next() {
		var i Blog
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Date,
			&i.Lang,
			&i.Duration,
			&i.Tags,
			&i.Description,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlogsByLang = `-- name: GetBlogsByLang :many
SELECT id, title, slug, date, lang, duration, tags, description, is_published, created_at, updated_at, content FROM blogs
WHERE is_published = true AND lang = $1
ORDER BY date DESC
LIMIT $2 OFFSET $3
`

type GetBlogsByLangParams struct {
	Lang   string `json:"lang"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetBlogsByLang(ctx context.Context, arg GetBlogsByLangParams) ([]Blog, error) {
	rows, err := q.db.Query(ctx, getBlogsByLang, arg.Lang, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Blog{}
	for rows.Next() {
		var i Blog
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Date,
			&i.Lang,
			&i.Duration,
			&i.Tags,
			&i.Description,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlogsByTag = `-- name: GetBlogsByTag :many
SELECT id, title, slug, date, lang, duration, tags, description, is_published, created_at, updated_at, content FROM blogs
WHERE is_published = true AND $1 = ANY(tags)
ORDER BY date DESC
LIMIT $2 OFFSET $3
`

type GetBlogsByTagParams struct {
	Tags   []string `json:"tags"`
	Limit  int32    `json:"limit"`
	Offset int32    `json:"offset"`
}

func (q *Queries) GetBlogsByTag(ctx context.Context, arg GetBlogsByTagParams) ([]Blog, error) {
	rows, err := q.db.Query(ctx, getBlogsByTag, arg.Tags, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Blog{}
	for rows.Next() {
		var i Blog
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Date,
			&i.Lang,
			&i.Duration,
			&i.Tags,
			&i.Description,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlogBySlug = `-- name: UpdateBlogBySlug :one
UPDATE blogs
SET title = $2, date = $3, lang = $4, duration = $5, tags = $6, description = $7, is_published = $8, content = $9, updated_at = NOW()
WHERE slug = $1
RETURNING id, title, slug, date, lang, duration, tags, description, is_published, created_at, updated_at, content
`

type UpdateBlogBySlugParams struct {
	Slug        string      `json:"slug"`
	Title       string      `json:"title"`
	Date        pgtype.Date `json:"date"`
	Lang        string      `json:"lang"`
	Duration    string      `json:"duration"`
	Tags        []string    `json:"tags"`
	Description pgtype.Text `json:"description"`
	IsPublished pgtype.Bool `json:"is_published"`
	Content     pgtype.Text `json:"content"`
}

func (q *Queries) UpdateBlogBySlug(ctx context.Context, arg UpdateBlogBySlugParams) (Blog, error) {
	row := q.db.QueryRow(ctx, updateBlogBySlug,
		arg.Slug,
		arg.Title,
		arg.Date,
		arg.Lang,
		arg.Duration,
		arg.Tags,
		arg.Description,
		arg.IsPublished,
		arg.Content,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Date,
		&i.Lang,
		&i.Duration,
		&i.Tags,
		&i.Description,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Content,
	)
	return i, err
}
