// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (user_id, post_slug, message)
VALUES ($1, $2, $3)
RETURNING id, user_id, post_slug, message, thumb_count, created_at, updated_at
`

type CreateMessageParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	PostSlug string      `json:"post_slug"`
	Message  string      `json:"message"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.UserID, arg.PostSlug, arg.Message)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostSlug,
		&i.Message,
		&i.ThumbCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = $1 AND user_id = $2
`

type DeleteMessageParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) error {
	_, err := q.db.Exec(ctx, deleteMessage, arg.ID, arg.UserID)
	return err
}

const deleteMessageBySuperUser = `-- name: DeleteMessageBySuperUser :exec
DELETE FROM messages
WHERE id = $1
`

func (q *Queries) DeleteMessageBySuperUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessageBySuperUser, id)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT 
  m.id, m.user_id, m.post_slug, m.message, m.thumb_count, m.created_at, m.updated_at,
  u.name AS user_name, u.picture_url AS user_picture_url,
  COALESCE(thumb_counts.count, 0) AS thumb_count
FROM messages m
JOIN users u ON m.user_id = u.id
LEFT JOIN (
  SELECT message_id, COUNT(*) AS count
  FROM message_thumbs
  GROUP BY message_id
) thumb_counts ON m.id = thumb_counts.message_id
WHERE m.id = $1
`

type GetMessageByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	PostSlug       string             `json:"post_slug"`
	Message        string             `json:"message"`
	ThumbCount     pgtype.Int4        `json:"thumb_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UserName       string             `json:"user_name"`
	UserPictureUrl pgtype.Text        `json:"user_picture_url"`
	ThumbCount_2   int64              `json:"thumb_count_2"`
}

func (q *Queries) GetMessageByID(ctx context.Context, id pgtype.UUID) (GetMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostSlug,
		&i.Message,
		&i.ThumbCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserPictureUrl,
		&i.ThumbCount_2,
	)
	return i, err
}

const getMessagesByBlogSlug = `-- name: GetMessagesByBlogSlug :many
SELECT 
  m.id, m.user_id, m.post_slug, m.message, m.thumb_count, m.created_at, m.updated_at,
  u.name AS user_name, u.picture_url AS user_picture_url,
  COALESCE(thumb_counts.count, 0) AS thumb_count
FROM messages m
JOIN users u ON m.user_id = u.id
LEFT JOIN (
  SELECT message_id, COUNT(*) AS count
  FROM message_thumbs
  GROUP BY message_id
) thumb_counts ON m.id = thumb_counts.message_id
WHERE m.post_slug = $1
ORDER BY m.created_at DESC
LIMIT $2 OFFSET $3
`

type GetMessagesByBlogSlugParams struct {
	PostSlug string `json:"post_slug"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

type GetMessagesByBlogSlugRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	PostSlug       string             `json:"post_slug"`
	Message        string             `json:"message"`
	ThumbCount     pgtype.Int4        `json:"thumb_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UserName       string             `json:"user_name"`
	UserPictureUrl pgtype.Text        `json:"user_picture_url"`
	ThumbCount_2   int64              `json:"thumb_count_2"`
}

// Note: blog slug now maps to post_slug directly
func (q *Queries) GetMessagesByBlogSlug(ctx context.Context, arg GetMessagesByBlogSlugParams) ([]GetMessagesByBlogSlugRow, error) {
	rows, err := q.db.Query(ctx, getMessagesByBlogSlug, arg.PostSlug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMessagesByBlogSlugRow{}
	for rows.Next() {
		var i GetMessagesByBlogSlugRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PostSlug,
			&i.Message,
			&i.ThumbCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserPictureUrl,
			&i.ThumbCount_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE messages
SET message = $2, updated_at = NOW()
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, post_slug, message, thumb_count, created_at, updated_at
`

type UpdateMessageParams struct {
	ID      pgtype.UUID `json:"id"`
	Message string      `json:"message"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessage, arg.ID, arg.Message, arg.UserID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PostSlug,
		&i.Message,
		&i.ThumbCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMessageThumbCount = `-- name: UpdateMessageThumbCount :exec
UPDATE messages 
SET thumb_count = (
  SELECT COUNT(*) 
  FROM message_thumbs 
  WHERE message_id = $1
)
WHERE id = $1
`

func (q *Queries) UpdateMessageThumbCount(ctx context.Context, messageID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateMessageThumbCount, messageID)
	return err
}
