// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message_thumbs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserThumbedMessage = `-- name: CheckUserThumbedMessage :one
SELECT EXISTS(
    SELECT 1 FROM message_thumbs
    WHERE message_id = $1 AND user_id = $2
)
`

type CheckUserThumbedMessageParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) CheckUserThumbedMessage(ctx context.Context, arg CheckUserThumbedMessageParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserThumbedMessage, arg.MessageID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createMessageThumb = `-- name: CreateMessageThumb :one
INSERT INTO message_thumbs (message_id, user_id)
VALUES ($1, $2)
ON CONFLICT (message_id, user_id) DO NOTHING
RETURNING id, message_id, user_id, created_at
`

type CreateMessageThumbParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateMessageThumb(ctx context.Context, arg CreateMessageThumbParams) (MessageThumb, error) {
	row := q.db.QueryRow(ctx, createMessageThumb, arg.MessageID, arg.UserID)
	var i MessageThumb
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessageThumb = `-- name: DeleteMessageThumb :exec
DELETE FROM message_thumbs
WHERE message_id = $1 AND user_id = $2
`

type DeleteMessageThumbParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteMessageThumb(ctx context.Context, arg DeleteMessageThumbParams) error {
	_, err := q.db.Exec(ctx, deleteMessageThumb, arg.MessageID, arg.UserID)
	return err
}

const getThumbCountForMessage = `-- name: GetThumbCountForMessage :one
SELECT COUNT(*) FROM message_thumbs
WHERE message_id = $1
`

func (q *Queries) GetThumbCountForMessage(ctx context.Context, messageID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getThumbCountForMessage, messageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
