// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Blog struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Slug        string             `json:"slug"`
	Date        pgtype.Date        `json:"date"`
	Lang        string             `json:"lang"`
	Duration    string             `json:"duration"`
	Tags        []string           `json:"tags"`
	Description pgtype.Text        `json:"description"`
	IsPublished pgtype.Bool        `json:"is_published"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Content     pgtype.Text        `json:"content"`
}

type DailyVisit struct {
	Date       pgtype.Date `json:"date"`
	VisitCount int32       `json:"visit_count"`
}

type Message struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	PostSlug   string             `json:"post_slug"`
	Message    string             `json:"message"`
	ThumbCount pgtype.Int4        `json:"thumb_count"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type MessageThumb struct {
	ID        pgtype.UUID        `json:"id"`
	MessageID pgtype.UUID        `json:"message_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Page struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID         pgtype.UUID        `json:"id"`
	GoogleID   string             `json:"google_id"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
	PictureUrl pgtype.Text        `json:"picture_url"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type VisitorHash struct {
	Date      pgtype.Date        `json:"date"`
	Hash      string             `json:"hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
