// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pages.sql

package db

import (
	"context"
)

const deletePageByName = `-- name: DeletePageByName :exec
DELETE FROM pages
WHERE name = $1
`

func (q *Queries) DeletePageByName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deletePageByName, name)
	return err
}

const getPageByName = `-- name: GetPageByName :one
SELECT id, name, content, created_at, updated_at FROM pages
WHERE name = $1
`

func (q *Queries) GetPageByName(ctx context.Context, name string) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByName, name)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPages = `-- name: ListPages :many
SELECT id, name, content, created_at, updated_at FROM pages
ORDER BY updated_at DESC
LIMIT $1 OFFSET $2
`

type ListPagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPages(ctx context.Context, arg ListPagesParams) ([]Page, error) {
	rows, err := q.db.Query(ctx, listPages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPage = `-- name: UpsertPage :one
INSERT INTO pages (name, content)
VALUES ($1, $2)
ON CONFLICT (name) DO UPDATE
SET content = EXCLUDED.content, updated_at = NOW()
RETURNING id, name, content, created_at, updated_at
`

type UpsertPageParams struct {
	Name    string `json:"name"`
	Content string `json:"content"`
}

func (q *Queries) UpsertPage(ctx context.Context, arg UpsertPageParams) (Page, error) {
	row := q.db.QueryRow(ctx, upsertPage, arg.Name, arg.Content)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
