// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckUserThumbedMessage(ctx context.Context, arg CheckUserThumbedMessageParams) (bool, error)
	CountBlogs(ctx context.Context) (int64, error)
	CountBlogsByTag(ctx context.Context, tags []string) (int64, error)
	CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateMessageThumb(ctx context.Context, arg CreateMessageThumbParams) (MessageThumb, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMessage(ctx context.Context, arg DeleteMessageParams) error
	DeleteMessageBySuperUser(ctx context.Context, id pgtype.UUID) error
	DeleteMessageThumb(ctx context.Context, arg DeleteMessageThumbParams) error
	GetAllBlogs(ctx context.Context, arg GetAllBlogsParams) ([]Blog, error)
	GetBlogByID(ctx context.Context, id pgtype.UUID) (Blog, error)
	GetBlogBySlug(ctx context.Context, slug string) (Blog, error)
	GetBlogWithMessageCountBySlug(ctx context.Context, slug string) (GetBlogWithMessageCountBySlugRow, error)
	GetBlogs(ctx context.Context, arg GetBlogsParams) ([]Blog, error)
	GetBlogsByLang(ctx context.Context, arg GetBlogsByLangParams) ([]Blog, error)
	GetBlogsByTag(ctx context.Context, arg GetBlogsByTagParams) ([]Blog, error)
	GetMessageByID(ctx context.Context, id pgtype.UUID) (GetMessageByIDRow, error)
	// Note: blog slug now maps to post_slug directly
	GetMessagesByBlogSlug(ctx context.Context, arg GetMessagesByBlogSlugParams) ([]GetMessagesByBlogSlugRow, error)
	GetMessagesByPostSlug(ctx context.Context, arg GetMessagesByPostSlugParams) ([]GetMessagesByPostSlugRow, error)
	GetThumbCountForMessage(ctx context.Context, messageID pgtype.UUID) (int64, error)
	GetUserByGoogleID(ctx context.Context, googleID string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	UpdateBlogBySlug(ctx context.Context, arg UpdateBlogBySlugParams) (Blog, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error)
	UpdateMessageThumbCount(ctx context.Context, messageID pgtype.UUID) error
	UpdateUserByGoogleID(ctx context.Context, arg UpdateUserByGoogleIDParams) (User, error)
}

var _ Querier = (*Queries)(nil)
