// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (google_id, email, name, picture_url)
VALUES ($1, $2, $3, $4)
RETURNING id, google_id, email, name, picture_url, created_at, updated_at
`

type CreateUserParams struct {
	GoogleID   string      `json:"google_id"`
	Email      string      `json:"email"`
	Name       string      `json:"name"`
	PictureUrl pgtype.Text `json:"picture_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.PictureUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, google_id, email, name, picture_url, created_at, updated_at FROM users
WHERE google_id = $1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_id, email, name, picture_url, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserByGoogleID = `-- name: UpdateUserByGoogleID :one
UPDATE users
SET email = $2, name = $3, picture_url = $4, updated_at = NOW()
WHERE google_id = $1
RETURNING id, google_id, email, name, picture_url, created_at, updated_at
`

type UpdateUserByGoogleIDParams struct {
	GoogleID   string      `json:"google_id"`
	Email      string      `json:"email"`
	Name       string      `json:"name"`
	PictureUrl pgtype.Text `json:"picture_url"`
}

func (q *Queries) UpdateUserByGoogleID(ctx context.Context, arg UpdateUserByGoogleIDParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserByGoogleID,
		arg.GoogleID,
		arg.Email,
		arg.Name,
		arg.PictureUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
