apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: tomlord-io
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: tomlord-io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17.5-alpine3.22
        env:
        - name: POSTGRES_DB
          value: "tomlord_minikube"
        - name: POSTGRES_USER
          value: "tomlord"
        - name: POSTGRES_PASSWORD
          value: "tomlord1122"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - tomlord
            - -d
            - tomlord_minikube
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - tomlord
            - -d
            - tomlord_minikube
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-storage
        emptyDir: {}