// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: message_thumbs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserThumbedMessage = `-- name: CheckUserThumbedMessage :one
SELECT EXISTS(
    SELECT 1 FROM message_thumbs
    WHERE message_id = $1 AND user_id = $2
)
`

type CheckUserThumbedMessageParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) CheckUserThumbedMessage(ctx context.Context, arg CheckUserThumbedMessageParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserThumbedMessage, arg.MessageID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createMessageThumb = `-- name: CreateMessageThumb :one
INSERT INTO message_thumbs (message_id, user_id)
VALUES ($1, $2)
ON CONFLICT (message_id, user_id) DO NOTHING
RETURNING id, message_id, user_id, created_at
`

type CreateMessageThumbParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateMessageThumb(ctx context.Context, arg CreateMessageThumbParams) (MessageThumb, error) {
	row := q.db.QueryRow(ctx, createMessageThumb, arg.MessageID, arg.UserID)
	var i MessageThumb
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMessageThumb = `-- name: DeleteMessageThumb :exec
DELETE FROM message_thumbs
WHERE message_id = $1 AND user_id = $2
`

type DeleteMessageThumbParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteMessageThumb(ctx context.Context, arg DeleteMessageThumbParams) error {
	_, err := q.db.Exec(ctx, deleteMessageThumb, arg.MessageID, arg.UserID)
	return err
}

const getMessageThumbsByUser = `-- name: GetMessageThumbsByUser :many
SELECT mt.id, mt.message_id, mt.user_id, mt.created_at, m.post_slug
FROM message_thumbs mt
JOIN messages m ON mt.message_id = m.id
WHERE mt.user_id = $1
ORDER BY mt.created_at DESC
LIMIT $2 OFFSET $3
`

type GetMessageThumbsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetMessageThumbsByUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	MessageID pgtype.UUID        `json:"message_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	PostSlug  string             `json:"post_slug"`
}

func (q *Queries) GetMessageThumbsByUser(ctx context.Context, arg GetMessageThumbsByUserParams) ([]GetMessageThumbsByUserRow, error) {
	rows, err := q.db.Query(ctx, getMessageThumbsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMessageThumbsByUserRow{}
	for rows.Next() {
		var i GetMessageThumbsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.UserID,
			&i.CreatedAt,
			&i.PostSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageThumbsWithUsers = `-- name: GetMessageThumbsWithUsers :many
SELECT mt.id, mt.message_id, mt.user_id, mt.created_at, u.name as user_name, u.picture_url as user_picture_url
FROM message_thumbs mt
JOIN users u ON mt.user_id = u.id
WHERE mt.message_id = $1
ORDER BY mt.created_at DESC
LIMIT $2 OFFSET $3
`

type GetMessageThumbsWithUsersParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type GetMessageThumbsWithUsersRow struct {
	ID             pgtype.UUID        `json:"id"`
	MessageID      pgtype.UUID        `json:"message_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UserName       string             `json:"user_name"`
	UserPictureUrl pgtype.Text        `json:"user_picture_url"`
}

func (q *Queries) GetMessageThumbsWithUsers(ctx context.Context, arg GetMessageThumbsWithUsersParams) ([]GetMessageThumbsWithUsersRow, error) {
	rows, err := q.db.Query(ctx, getMessageThumbsWithUsers, arg.MessageID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMessageThumbsWithUsersRow{}
	for rows.Next() {
		var i GetMessageThumbsWithUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.UserID,
			&i.CreatedAt,
			&i.UserName,
			&i.UserPictureUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThumbCountForMessage = `-- name: GetThumbCountForMessage :one
SELECT COUNT(*) FROM message_thumbs
WHERE message_id = $1
`

func (q *Queries) GetThumbCountForMessage(ctx context.Context, messageID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getThumbCountForMessage, messageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
