// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckUserThumbedMessage(ctx context.Context, arg CheckUserThumbedMessageParams) (bool, error)
	CountMessagesByPostSlug(ctx context.Context, postSlug string) (int64, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateMessageThumb(ctx context.Context, arg CreateMessageThumbParams) (MessageThumb, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteMessage(ctx context.Context, arg DeleteMessageParams) error
	DeleteMessageThumb(ctx context.Context, arg DeleteMessageThumbParams) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetMessageByID(ctx context.Context, id pgtype.UUID) (GetMessageByIDRow, error)
	GetMessageThumbsByUser(ctx context.Context, arg GetMessageThumbsByUserParams) ([]GetMessageThumbsByUserRow, error)
	GetMessageThumbsWithUsers(ctx context.Context, arg GetMessageThumbsWithUsersParams) ([]GetMessageThumbsWithUsersRow, error)
	GetMessagesByPostSlug(ctx context.Context, arg GetMessagesByPostSlugParams) ([]GetMessagesByPostSlugRow, error)
	GetMessagesByUser(ctx context.Context, arg GetMessagesByUserParams) ([]GetMessagesByUserRow, error)
	GetThumbCountForMessage(ctx context.Context, messageID pgtype.UUID) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserByGoogleID(ctx context.Context, arg UpdateUserByGoogleIDParams) (User, error)
}

var _ Querier = (*Queries)(nil)
